name: Trigger auto deployment for mbpdbcontainer

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_PAT }} # Set for all steps in this job
    
    services:
      redis:
        image: redis:latest
        ports:
          - 6379:6379
    steps:
    - name: Checkout to the branch
      uses: actions/checkout@v2

    - name: Azure Login
      uses: azure/login@v1
      with:
          creds: ${{ secrets.MBPDBCONTAINER_AZURE_CREDENTIALS }}

    # Pass the GitHub PAT as a build argument to Docker
    - name: Build and push container image to registry
      uses: azure/container-apps-deploy-action@v1
      with:
          appSourcePath: .
          registryUrl: docker.io
          registryUsername: ${{ secrets.MBPDBCONTAINER_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.MBPDBCONTAINER_REGISTRY_PASSWORD }}
          containerAppName: mbpdbcontainer
          resourceGroup: COH_MBPDB_RG
          imageToBuild: mbpdb/mbpdb:latest
          dockerfilePath: Dockerfile

      env:
        GITHUB_PAT: ${{ secrets.GITHUB_PAT }}

    - name: Update Azure Container App
      run: |
          az containerapp update \
                    --name mbpdbcontainer \
                    --resource-group COH_MBPDB_RG \
                    --image docker.io/mbpdb/mbpdb:latest
