name: Trigger auto deployment for mbpdbcontainer

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout to the branch
      uses: actions/checkout@v2

    - name: Azure Login
      uses: azure/login@v1
      with:
          creds: ${{ secrets.MBPDBCONTAINER_AZURE_CREDENTIALS }}

    # Pass the GitHub PAT as a build argument to Docker
    - name: Build and push container image to registry
      uses: azure/container-apps-deploy-action@v1
      with:
          appSourcePath: .
          registryUrl: docker.io
          registryUsername: ${{ secrets.MBPDBCONTAINER_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.MBPDBCONTAINER_REGISTRY_PASSWORD }}
          containerAppName: mbpdbcontainer
          resourceGroup: mbpdb
          imageToBuild: kuhfeldrf/peptide_sqlite3:latest
          dockerfilePath: Dockerfile
          buildArgs: GITHUB_PERSONAL_ACCESS_TOKEN=${{ secrets.GITHUB_PAT }}  # Assuming GITHUB_PAT is your GitHub secret

    # Use GitHub PAT for Git operations (optional)
    - name: Git Operations
      run: |
        git config --global user.email "kuhfeldrf@gmail.com"
        git config --global user.name "Rusty"
        git remote add origin https://${{ secrets.GITHUB_PAT }}@github.com/kuhfeldrf/MBPDB.git
        git push origin main
      env:
        GITHUB_PAT: ${{ secrets.GITHUB_PAT }}

    - name: Update Azure Container App
      run: |
        az containerapp update --resource-group mbpdb --name mbpdbcontainer --image kuhfeldrf/peptide_sqlite3:latest
