name: Trigger auto deployment for mbpdbcontainer

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.MY_GITHUB_PAT }} # Set for all steps in this job
    
    services:
      redis:
        image: redis:latest
        ports:
          - 6379:6379
    steps:
    - name: Checkout to the branch
      uses: actions/checkout@v2

    - name: Azure Login
      uses: azure/login@v1
      with:
          creds: ${{ secrets.MBPDBCONTAINER_AZURE_CREDENTIALS_UPDATED }}

    # Pass the GitHub PAT as a build argument to Docker
    - name: Build and push container image to registry
      uses: azure/container-apps-deploy-action@v1
      with:
        appSourcePath: .
        registryUrl: docker.io
        registryUsername: ${{ secrets.MBPDBCONTAINER_REGISTRY_USERNAME }}
        registryPassword: ${{ secrets.MBPDBCONTAINER_REGISTRY_PASSWORD }}
        containerAppName: mbpdbcontainer
        resourceGroup: COH_MBPDB_RG
        imageToBuild: mbpdb/mbpdb:latest
        dockerfilePath: Dockerfile
        targetPort: 8000
        ingress: external
        env: |
          WEBSITES_PORT=8000
          WEBSITES_CONTAINER_START_TIME_LIMIT=1800

    - name: Update Azure Container App with multi-port configuration
      run: |
        az containerapp update \
          --name mbpdbcontainer \
          --resource-group COH_MBPDB_RG \
          --image docker.io/mbpdb/mbpdb:latest \
          --ingress external \
          --target-port 8000 \
          --additional-ports 8866 \
          --query-parameters \
          --set-env-vars \
            WEBSITES_PORT=8000 \
            WEBSITES_CONTAINER_START_TIME_LIMIT=1800

    - name: Configure Container App Scale Rules
      run: |
        az containerapp update \
          --name mbpdbcontainer \
          --resource-group COH_MBPDB_RG \
          --min-replicas 1 \
          --max-replicas 3 \
          --cpu 2 \
          --memory 4Gi

