name: Deploy Django-Voila Container to Azure

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.MY_GITHUB_PAT }}
    
    services:
      redis:
        image: redis:latest
        ports:
          - 6379:6379

    steps:
    - name: Checkout to the branch
      uses: actions/checkout@v2

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.MBPDBCONTAINER_AZURE_CREDENTIALS_UPDATED }}

    - name: Build and push container image to registry
      uses: azure/container-apps-deploy-action@v1
      with:
        appSourcePath: .
        registryUrl: docker.io
        registryUsername: ${{ secrets.MBPDBCONTAINER_REGISTRY_USERNAME }}
        registryPassword: ${{ secrets.MBPDBCONTAINER_REGISTRY_PASSWORD }}
        containerAppName: mbpdbcontainer
        resourceGroup: COH_MBPDB_RG
        imageToBuild: mbpdb/mbpdb:latest
        dockerfilePath: Dockerfile
        targetPort: 8000
        ingress: external
        env: |
          WEBSITES_PORT=8000
          WEBSITES_CONTAINER_START_TIME_LIMIT=1800

    - name: Enable multi-port ingress
      run: |
        az containerapp ingress update \
          --name mbpdbcontainer \
          --resource-group COH_MBPDB_RG \
          --target-port 8000 \
          --additional-ports 8866 \
          --exposed-port 8866 \
          --transport http \
          --type external

    - name: Configure DNS for Voila
      run: |
        az containerapp hostname add \
          --name mbpdbcontainer \
          --resource-group COH_MBPDB_RG \
          --hostname "voila.mbpdb.nws.oregonstate.edu"

    - name: Update environment variables
      run: |
        az containerapp update \
          --name mbpdbcontainer \
          --resource-group COH_MBPDB_RG \
          --cpu 1.0 \
          --memory 2.0Gi \
          --set-env-vars \
          DJANGO_SETTINGS_MODULE=peptide.settings \
          PYTHONPATH=/app/include/peptide \
          WEBSITES_PORT=8000 \
          WEBSITES_CONTAINER_START_TIME_LIMIT=1800 \
          VOILA_PORT=8866
