name: Trigger auto deployment for mbpdbcontainer

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      - main
    paths:
      - 'dockerfile/**'
      - '.github/workflows/mbpdbcontainer-AutoDeployTrigger-61dd0fa8-0273-4290-9035-02fe5b1c02ff.yml'

  # Allow manual trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.MBPDBCONTAINER_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry  # Fixed indentation here
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace }}/dockerfile 
          registryUrl: docker.io
          registryUsername: ${{ secrets.MBPDBCONTAINER_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.MBPDBCONTAINER_REGISTRY_PASSWORD }}
          containerAppName: mbpdbcontainer
          resourceGroup: mbpdb
          imageToBuild: kuhfeldrf/peptide_sqlite3:mbpdbcontainer-${{ github.sha }}
          dockerfilePath: Dockerfile
