name: Trigger auto deployment for mbpdbcontainer

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2  # Using the latest stable version

      - name: Azure Login
        uses: azure/login@v1  # Using the latest stable version
        with:
          client-id: ${{ secrets.MBPDBCONTAINER_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.MBPDBCONTAINER_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.MBPDBCONTAINER_AZURE_SUBSCRIPTION_ID }}

      # ... (rest of your steps)
